version: "3"

services:
  nginx:
    build: ./nginx/.
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - php
    links:
      - php

  php:
    build: ./php/.
    container_name: php
    volumes:
      - ./html:/html
      - ./logs/php:/var/log/php
    depends_on:
      - mysql
      - redis
    links:
      - mysql
      - redis

  mysql:
    build: ./mysql/.
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - ./mysql/.env
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:4
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  mysql-data:
    driver: local
